jQuery(function($){
$(document).ready(function(){
  $('.toggle').click(function(){
	$(this).next('.toggle-menu').toggleClass('visible');
	$(this).toggleClass('visible');
	$('.toggle2').removeClass('visible2');
  });
  $('.toggle2').click(function(){
	$(this).toggleClass('visible2');
	$(this).siblings().removeClass('visible2');
  });
});
});